# camera_bridge/config/rtsp_params.yaml
image2rtsp:
  ros__parameters:
    # CompressedImage 사용
    compressed: True
    topic: "/camera/image_raw/compressed"
    
    # RTSP 서버 설정
    mountpoint: "/camera"
    port: 8554
    
    # CompressedImage용 파이프라인
    compressed_pipeline: |
      ( appsrc name=imagesrc do-timestamp=true min-latency=0 max-latency=0 
        max-bytes=1000 is-live=true ! 
        jpegdec ! videoconvert ! videoscale ! 
        video/x-raw, framerate=30/1, width=640, height=480 ! 
        x264enc tune=zerolatency bitrate=1000 speed-preset=ultrafast key-int-max=30 ! 
        video/x-h264, profile=baseline ! 
        rtph264pay name=pay0 pt=96 )
