version: '3.8'

services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wsl_ros2
    network_mode: host
    
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0                          # ⭐ 라즈베리파이, Qt와 동일하게
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp    # ⭐ CycloneDDS 명시
    
    volumes:
      - ../src:/root/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/shm:/dev/shm                        # ⭐ 공유 메모리 마운트 추가
    
    stdin_open: true
    tty: true
    
    # ⭐ 자동 빌드 추가
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        cd /root/ros2_ws &&
        if [ -d src ]; then
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
          source install/setup.bash
        fi &&
        exec bash
      "
