version: '3.8'

services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wsl_ros2
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=42
      - ROS_LOCALHOST_ONLY=0
    volumes:
      - ../src:/root/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
    command: /bin/bash
